mobvis_web/frontpage/urls.py
from django.urls import path

from . import views

app_name = 'frontpage'

urlpatterns = [
    path('', views.starting_page, name='home'),
    path('demo/', views.demo_page, name='demo')
]

mobvis_web/mobvis_web/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontpage.urls'), name='home')
]

mobvis_web/frontpage/models.py
from django.db import models

# Create your models here.

mobvis_web/frontpage/views.py
from django.shortcuts import render

import pandas as pd

from .connect import mobvis_connection

def starting_page(request):
    context = {}

    if request.method == 'POST':
        trace = None
        configurations = []
        metrics = []
        plots = []
        display_metrics = []

        if request.POST.getlist('column_names'):
            trace = pd.read_csv(request.FILES['trace'], sep=',')
        else:
            names = [
                request.POST.get('first-column'),
                request.POST.get('second-column'),
                request.POST.get('third-column'),
                request.POST.get('fourth-column')
            ]
            
            trace = pd.read_csv(request.FILES['trace'], sep=',', names=names)
        
        print('\nUploaded trace: \n')
        print(trace.head())

        # 0: max_distance
        # 1: pause_threshold
        # 2: contact_radius
        # 3: distance_formula
        configurations = check_configurations(request.POST.getlist('configuration'))

        metrics = request.POST.getlist('metric')

        plots = request.POST.getlist('plot')

        display_metrics = request.POST.getlist('display_metrics')

        context = mobvis_connection(trace, configurations, metrics, plots, display_metrics)

    return render(request, 'home.html', context)

def check_configurations(configurations):
    if not configurations[0]:
        configurations[0] = 30
    if not configurations[1]:
        configurations[1] = 10
    if not configurations[2]:
        configurations[2] = 20
    if not configurations[3]:
        configurations[3] = 'euclidean'

    return configurations

def demo_page(request):
    return render(request, 'demo.html', {})

mobvis_web/frontpage/templates/demo.html
{% extends 'index.html' %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/demo-style.css' %}">
{% endblock extrahead %}

{% block content %}

<img class="work-image" src="{% static 'imgs/icons/construction.svg' %}" alt="Work in progress" />

<div class="dev-phrase">
    Page under development!
</div>

{% endblock content %}

mobvis_web/frontpage/templates/frontpage/home.html
{% extends 'frontpage/index.html' %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'frontpage/css/homepage-style.css' %}">
{% endblock extrahead %}

{% block content %}
<div class="std-box" id="general-instructions">
    <img src="{% static 'frontpage/imgs/icons/paper.svg' %}" alt="General Instructions" />
    <p>General instructions:</p>

    <ol>
        <li>Upload the trace in CSV format via the "Upload" button;</li>
        <li>Select metrics and configure parameters for processing (if not specified, parameters are set   to a default value);</li>
        <li>Select the plots to be generated;</li>
        <li>Press the "Submit" button to start the procedures.</li>
    </ol>
</div>

<div class="std-box" id="upload-raw">
    <img src="{% static 'frontpage/imgs/icons/file.svg' %}" alt="Upload Raw Trace" />
    <p>Upload raw trace:</p>
    <div id="drag-drop">Drag and drop here or</div>
    <button>Select from computer</button>
</div>

<button>UPLOAD</button>

<div class="std-box" id="configuration">
    <img src="{% static 'frontpage/imgs/icons/config.svg' %}" alt="Configuration Parameters" />
    <p>Configuration parameters:</p>
    <ul id="parameters">
        <li>
            <span class="help">?
                <div class="help-text">
                    Maximum distance to a region be considered a Stay-location.
                </div>
            </span>
            Max distance: 
        </li><input type="text" placeholder="default = 30 m">
        <li>
            <span class="help">?
                <span class="help-text">
                    Ammout of waiting time to the Stay-location be considered a Geo-location (in minutes).
                </span>
            </span>
            Pause threshold: 
        </li><input type="text" placeholder="default = 10 min">
        <li>
            <span class="help">?
                <span class="help-text">
                    Contact radius of the nodes.
                </span>
            </span>
            Contact radius: 
        </li><input type="text" placeholder="default = 20 m">
        <li>
            <span class="help">?
                <span class="help-text">
                    Distance formula. Supported types are: Haversine and Euclidean.
                </span>
            </span>
            Distance formula: 
        </li><input type="text" placeholder="default = euclidean">
        <li>
            <span class="help">?
                <span class="help-text">
                    This configuration parameter will still be added.
                </span>
            </span>
            To be added: 
        </li><input type="text" placeholder="default = NaN">
    </ul>
</div>

<div class="std-box" id="metrics">
    <img src="{% static 'frontpage/imgs/icons/calc.png' %}" alt="Choose Metrics">
    <p>Choose metrics: </p>

    <div class="metric-types">Spatial: 
        <div class="metric"><input type="checkbox" />Travel Distance</div>
        <div class="metric"><input type="checkbox" />Radius of Gyration</div>
        <!-- <div class="metric"><input type="checkbox" />Total Distance</div> -->
    </div>
    <div class="metric-types">Temporal: 
        <div class="metric"><input type="checkbox" />Travel Time</div>
        <div class="metric"><input type="checkbox" />Visit Time</div>
    </div>
    <div class="metric-types">Social:
        <div class="metric"><input type="checkbox" />Intercontact Time</div>
        <div class="metric"><input type="checkbox" />Contact Duration</div>
    </div>
    <div class="metric-types">Spatiotemporal: 
        <div class="metric"><input type="checkbox" />Visit Order</div>
        <div class="metric"><input type="checkbox" />Average Speed</div>
    </div>
</div>

<div class="std-box" id="plots">
    <img src="{% static 'frontpage/imgs/icons/chart.png' %}" alt="Select Plots" />
    <p>Select plots: </p>
    <ul id="select-plots">
        <li>
            <span class="help">?
                <span class="help-text">
                    Plots statistical graphs and histograms about the extracted metrics.
                </span>
            </span><input type="checkbox" checked>
            Statistical plots (metrics)
        </li>
        <li>
            <span class="help">?
                <span class="help-text">
                    Plots spatial graphs about the trace.
                </span>
            </span><input type="checkbox" checked>
            Spatial plots (metrics)
        </li>
        <li>
            <span class="help">?
                <span class="help-text">
                    Select plots manually.
                </span>
            </span><input type="checkbox">
            Specify plots
        </li>
    </ul>
</div>

{% endblock content %}

mobvis_web/frontpage/templates/home.html
{% extends 'index.html' %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/homepage-style.css' %}">
{% endblock extrahead %}

{% block content %}
<div class="std-box" id="general-instructions">
    <img src="{% static 'imgs/icons/paper.svg' %}" alt="General Instructions" />
    <p>General instructions:</p>

    <ol>
        <li>Upload the trace in CSV format via the "Upload" button;</li>
        <li>Select the metrics and set the configuration parameters for processing (if not specified, the parameters will be set to a default value);</li>
        <li>Select the plots to be generated;</li>
        <li>Press the "Submit" button to start the procedures.</li>
    </ol>
</div>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="std-box" id="upload-raw">
        <img src="{% static 'imgs/icons/file.svg' %}" alt="Upload Raw Trace" />
        <p>Upload raw trace:</p>
        <div id="drag-drop">Drag and drop here or</div>
        <label for="file-input">Select from computer</label>
        <input type="file" id="file-input" name="trace"/>
        <div class="middle-question" id="column-names">
            <input type="checkbox" checked name="column_names" value="names" onclick="columnsController()">
            Does the trace have column names?
        </div>
        <div class="columns" style="display: none;" id="columns-div">
            <p style="font-weight:600; font-size: 24px;">Select the corresponding names of the four key columns (ex.: timestamp, id, x, y) in the order that they are in the trace.</p>
            <p>IMPORTANT: If the trace contains more than four columns, you can either name all of them before sending them to MobVis, or remove the non-key columns and enter the remaining columns names in order through this submenu.</p>
            <select name="first-column" id="first-column">
                <optgroup label="First Column">
                    <option value="timestamp" selected>timestamp</option>
                    <option value="datetime">datetime</option>
                    <option value="id">id</option>
                    <option value="x">x</option>
                    <option value="y">y</option>
                    <option value="lat">latitude</option>
                    <option value="lng">longitude</option>
                </optgroup>
            </select>
            <select name="second-column" id="second-column">
                <optgroup label="Second Column">
                    <option value="timestamp">timestamp</option>
                    <option value="datetime">datetime</option>
                    <option value="id" selected>id</option>
                    <option value="x">x</option>
                    <option value="y">y</option>
                    <option value="lat">latitude</option>
                    <option value="lng">longitude</option>
                </optgroup>
            </select>
            <select name="third-column" id="third-column">
                <optgroup label="Third Column">
                    <option value="timestamp">timestamp</option>
                    <option value="datetime">datetime</option>
                    <option value="id">id</option>
                    <option value="x" selected>x</option>
                    <option value="y">y</option>
                    <option value="lat">latitude</option>
                    <option value="lng">longitude</option>
                </optgroup>
            </select>
            <select name="fourth-column" id="fourth-column">
                <optgroup label="Fourth Column">
                    <option value="timestamp">timestamp</option>
                    <option value="datetime">datetime</option>
                    <option value="id">id</option>
                    <option value="x">x</option>
                    <option value="y" selected>y</option>
                    <option value="lat">latitude</option>
                    <option value="lng">longitude</option>
                </optgroup>
            </select>
            <button type="button" onclick="columnsController()">HIDE</button>
        </div>
    </div>

    <!-- <button type="submit">UPLOAD</button> -->

    <div class="std-box" id="configuration">
        <img src="{% static 'imgs/icons/config.svg' %}" alt="Configuration Parameters" />
        <p>Configuration parameters:</p>
        <ul id="parameters">
            <li>
                <span class="help">?
                    <div class="help-text">
                        Maximum distance to a region be considered a Stay-location.
                    </div>
                </span>
                Max distance: 
            </li><input type="text" placeholder="default = 30 m" name="configuration">
            <li>
                <span class="help">?
                    <span class="help-text">
                        Ammout of waiting time to the Stay-location be considered a Geo-location (in minutes).
                    </span>
                </span>
                Pause threshold: 
            </li><input type="text" placeholder="default = 10 min" name="configuration">
            <li>
                <span class="help">?
                    <span class="help-text">
                        Contact radius of the nodes.
                    </span>
                </span>
                Contact radius: 
            </li><input type="text" placeholder="default = 20 m" name="configuration">
            <li>
                <span class="help">?
                    <span class="help-text">
                        Distance formula. Supported types are: Haversine and Euclidean.
                    </span>
                </span>
                Distance formula: 
            </li><input type="text" placeholder="default = euclidean" name="configuration">
            <!-- <li>
                <span class="help">?
                    <span class="help-text">
                        This configuration parameter will still be added, leave empty.
                    </span>
                </span>
                To be added: 
            </li><input type="text" placeholder="default = NaN"> -->
        </ul>
    </div>
    
    <div class="std-box" id="metrics">
        <img src="{% static 'imgs/icons/calculator.svg' %}" alt="Choose Metrics" />
        <p>Choose metrics: </p>
    
        <div class="metric-types">Spatial: 
            <div class="metric"><input type="checkbox" name="metric" value="TRVD" />Travel Distance</div>
            <div class="metric"><input type="checkbox" name="metric" value="RADG" />Radius of Gyration</div>
            <!-- <div class="metric"><input type="checkbox" name="TOTD" />Total Distance</div> -->
        </div>
        <div class="metric-types">Temporal: 
            <div class="metric"><input type="checkbox" name="metric" value="TRVT" />Travel Time</div>
            <div class="metric"><input type="checkbox" name="metric" value="VIST" />Visit Time</div>
        </div>
        <div class="metric-types">Social:
            <div class="metric"><input type="checkbox" name="metric" value="INCO" />Intercontact Time</div>
            <div class="metric"><input type="checkbox" name="metric" value="CODU" />Contact Duration</div>
        </div>
        <div class="metric-types">Spatiotemporal: 
            <div class="metric"><input type="checkbox" name="metric" value="VISO" />Visit Order</div>
            <div class="metric"><input type="checkbox" name="metric" value="ASPD" />Average Speed</div>
        </div>
        <div class="middle-question" id="display-metrics">
            <input type="checkbox" checked name="display_metrics" value="display">
            Display Tables
        </div>
    </div>
    
    <div class="std-box" id="plots">
        <img src="{% static 'imgs/icons/chart.svg' %}" alt="Select Plots" />
        <p>Select plots: </p>
        <ul id="select-plots">
            <li>
                <span class="help">?
                    <span class="help-text">
                        Plots statistical graphs and histograms about the extracted metrics.
                    </span>
                </span><input type="checkbox" checked name="plot" value="statistical">
                Statistical plots (metrics)
            </li>
            <li>
                <span class="help">?
                    <span class="help-text">
                        Plots spatial graphs about the trace.
                    </span>
                </span><input type="checkbox" checked name="plot" value="spatial">
                Spatial plots (trace)
            </li>
            <!-- <li>
                <span class="help">?
                    <span class="help-text">
                        Select plots manually.
                    </span>
                </span><input type="checkbox">
                Specify plots
            </li> -->
        </ul>
    </div>
    <button type="submit" id="submit-button">SUBMIT</button>
</form>

{% if tables and display_metrics %}
<h2 class="media-division"><img src="{% static 'imgs/icons/table.svg' %}" alt="Tables Content" />Tables: Metrics Data</h2>
    <div class="table-scroller">
    {% for table in tables %}
        <div class="table-element">
            {{ table|safe }}
            <button id="download-button">DOWNLOAD</button>
        </div>
    {% endfor %}
    </div>
{% endif %}

{% if figures_spatial %}
<h2 class="media-division"><img src="{% static 'imgs/icons/gps.svg' %}" alt="Spatial Figures Content" />Figures: Spatial Plots</h2>
    <div class="figure-scroller">
    {% for figure in figures_spatial %}
        <div class="figure-element">
            {{ figure|safe }}
            <button id="download-button">DOWNLOAD</button>
        </div>
    {% endfor %}
    </div>
{% endif %}

{% if figures_statistical %}
<h2 class="media-division"><img src="{% static 'imgs/icons/boxplot.svg' %}" alt="Spatial Figures Content" />Figures: Statistical Plots</h2>
    <div class="figure-scroller">
    {% for figure in figures_statistical %}
        <div class="figure-element">
            {{ figure|safe }}
            <button id="download-button">DOWNLOAD</button>
        </div>
    {% endfor %}
    </div>
{% endif %}

{% endblock content %}

mobvis_web/frontpage/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MobVis: Easily visualize mobility data</title>
    <link rel="stylesheet" href="{% static 'css/header-style.css' %}">
    <link rel="icon" href="{% static 'imgs/small_logo.svg' %}">
    <script src="{% static 'js/scripts.js' %}"></script>
    {% block extrahead %}
        Specific head configurations here!
    {% endblock extrahead %}
</head>
<body>
    <header>
        <div class="top-bar"></div>
        <div class="top-circles" id="circle1"></div>
        <div class="top-circles" id="circle2"></div>

       <img src="{% static 'imgs/full_logo.svg' %}"
            alt="MobVis Logo"
            class="top-logo"
            title="MobVis: A framework to easily visualize mobility data" />

        <span class="top-phrase">A framework to easily visualize mobility data</span>
        <div class="navbar-bar"></div>

        <nav class="navbar">
            <a href="{% url 'frontpage:home' %}">HOME</a>
            <a href="{% url 'frontpage:demo' %}">DEMO</a>
            <a href="project.html">PROJECT</a>
            <a href="contact.html">CONTACT</a>
        </nav>
    </header>
    {% block content %}
        Current page content here!
    {% endblock content %}
    <footer>
        <img src="{% static 'imgs/full_logo.svg' %}"
                alt="MobVis Logo"
                class="bottom-logo"
                title="MobVis: A framework to easily visualize mobility data" />

        <a href="https://github.com/lucNovais/MobVis" target="_blank">
            <img src="{% static 'imgs/icons/github.svg' %}"
                 alt="GitHub Page"
                 class="github-logo"
                 title="Visit our GitHub page!" />
        </a>

        <div class="thanks-phrase">
            This project was developed thanks to the support of:
        </div>

        <div class="institutions">
            <a href="https://ufop.br/" target="_blank">
                <img src="{% static 'imgs/logo_ufop.png' %}"
                     alt="UFOP Logo"
                     class="logo"
                     id="ufop"
                     title="Universidade Federal de Ouro Preto" />
            </a>
            <a href="https://www.fkie.fraunhofer.de/" target="_blank">
                <img src="{% static 'imgs/logo_fkie.png' %}"
                     alt="FKIE Logo"
                     class="logo"
                     id="fkie"
                     title="Fraunhofer-Institut für Kommunikation, Informationsverarbeitung und Ergonomie FKIE" />
            </a>
            <a href="https://www.ufes.br/" target="_blank">
                <img src="{% static 'imgs/logo_ufes.png' %}"
                     alt="UFES Logo"
                     class="logo"
                     id="ufes"
                     title="Universidade Federal do Espírito Santo" />
            </a>
            <a href="http://www.fapemig.br/pt/" target="_blank">
                <img src="{% static 'imgs/logo_fapemig.png' %}"
                     alt="FAPEMIG Logo"
                     class="logo"
                     id="fapemig"
                     title="FAPEMIG" />
            </a>
        </div>
    </footer>
</body>
</html>